server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/project-estimation-system
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false



app.security.jwt-secret=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
app.security.jwt-expiration-seconds=86400


pandoc.executable=C:/Users/BeasDeveloper/AppData/Local/Pandoc/pandoc.exe
pandoc.temp-dir=proposal-conversions

proposal.storage.path=D:/proposal-storage