server.port=8080

######## Db Source ####################
spring.datasource.url=jdbc:postgresql://localhost:5432/project_estimation
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false


#### Logger path setup ####
base_location=D:\\project_estimation
log_file_path=\\project_estimation\\log
log_file_name=project_estimation


pandoc.executable=C:/Users/BeasDeveloper/AppData/Local/Pandoc/pandoc.exe
pandoc.temp-dir=proposal-conversions

proposal.storage.path=D:/proposal-storage

psr.storage-dir=C:/project-estimation/psr


############################ File Upload #######################################
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Maximum file size per request
spring.servlet.multipart.max-file-size=15MB
# Maximum total request size for multipart requests
spring.servlet.multipart.max-request-size=10MB
# Local directory path where files will be stored
file.upload-dir=D:/proposal-storage/uploads

